### ISSUE TITLE
Different Results

### ISSUE THREAD

**Issue by ZhaoBeilan825** [Guojyjy/CoTV#9]
Hello, your code really helps me understand the traffic light signal control. These days I try to run your codes in 1x1 grid and 1x6 grid with the CoTV and PressLight, but why are the metric "Fuel consumption(l/100km)" results  in my training quite different with your results described in the paper? I haven't do any modification in the code. Looking forward to communicating with you. Thanks very much.
![2024-01-11 09-35-36 的屏幕截图](https://github.com/Guojyjy/CoTV/assets/55695845/c5f3e190-9b5e-493d-8f68-180ac708cde0)

**Comment by Darkerok** [comment]
> 您好，您的代码确实帮助我理解了交通灯信号控制。这几天我尝试使用 CoTV 和 PressLight 在 1x1 网格和 1x6 网格中运行您的代码，但为什么我训练中的指标“消耗消耗（ l/100km）”结果与论文中描述的结果完全不同？我没有对代码做任何修改期待。与您的交流。非常感谢。 ![2024-01-11 09-35-36 的屏幕截图](https://private-user-images.githubusercontent.com/55695845/296104624-c5f3e190-9b5e-493d-8f68-180ac708cde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjQzOTEsIm5iZiI6MTcwOTAyNDA5MSwicGF0aCI6Ii81NTY5NTg0NS8yOTYxMDQ2MjQtYzVmM2UxOTAtOWI1ZS00OTNkLThmNjgtMTgwYWM3MDhjZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjEyYWZiYTUyMTBkZmZmMDZmNTM1OWUxOWJhNzUwYjBkMzFkZWI2N2NlMDQyYzc0ZDBiZDIxMWE3MTI3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkPyQKN-XD-0BzsF66mKHzUbmBtNbMIaDg3Jjm3_HWs)

您好，看到您配置环境成功，向请教您一下，我在运行python examples/train_ppo.py CoTV_grid --num_steps 150语句后遇到了这样的问题
![image](https://github.com/Guojyjy/CoTV/assets/76843947/1efcd9d8-1a1c-49a7-9a89-10a9cea41756)
向请教您该怎么解决

**Comment by ZhipuChen-Steve** [comment]
Hello, could you please share your "pip list" of the "flow" environment? Following the tutorial, I have some problems replicating the experiment, thanks a lot.

**Comment by Guojyjy** [comment]
> Hello, your code really helps me understand the traffic light signal control. These days I try to run your codes in 1x1 grid and 1x6 grid with the CoTV and PressLight, but why are the metric "Fuel consumption(l/100km)" results in my training quite different with your results described in the paper? I haven't do any modification in the code. Looking forward to communicating with you. Thanks very much.
> ![2024-01-11 09-35-36 的屏幕截图](https://private-user-images.githubusercontent.com/55695845/296104624-c5f3e190-9b5e-493d-8f68-180ac708cde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2ODI5MjAsIm5iZiI6MTcxNDY4MjYyMCwicGF0aCI6Ii81NTY5NTg0NS8yOTYxMDQ2MjQtYzVmM2UxOTAtOWI1ZS00OTNkLThmNjgtMTgwYWM3MDhjZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDIwNDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODU0N2U1NzE1ZGRlMWE5ZmNjODVkNGY4ZmU2ZmY5Y2Q2OGFlMjg3MGQxMDkyZDI5MDQxMWM5MDQ1YzJlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sG6g8JIhCnNpemvM5EnHeIGaRoFUTKm17stEpnCA2IU)

The difference in "Fuel consumption (l/100km)" metrics between your training results and those in the CoTV paper is due to updates of SUMO output files: changed the unit of fuel consumption measurements `fuel_abs` from **ml** to **mg**. 

This change affects the output files and the evaluation results obtained from _CoTV/evaluation/getResults.py_, but does not alter the conclusions drawn in the CoTV paper.

For more detailed information on these output parameters, please refer to the SUMO documentation:
- <https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html>
- <https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html>.

**Comment by Guojyjy** [comment]
> Hello, could you please share your "pip list" of the "flow" environment? Following the tutorial, I have some problems replicating the experiment, thanks a lot.

[requirements.txt](https://github.com/Guojyjy/CoTV/files/15194013/requirements.txt) for the pip list on Linux (Ubuntu 20.04.2)

**Comment by xulw8** [comment]
> Hello, your code really helps me understand the traffic light signal control. These days I try to run your codes in 1x1 grid and 1x6 grid with the CoTV and PressLight, but why are the metric "Fuel consumption(l/100km)" results in my training quite different with your results described in the paper? I haven't do any modification in the code. Looking forward to communicating with you. Thanks very much. ![2024-01-11 09-35-36 的屏幕截图](https://private-user-images.githubusercontent.com/55695845/296104624-c5f3e190-9b5e-493d-8f68-180ac708cde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODg5MzgsIm5iZiI6MTcyOTY4ODYzOCwicGF0aCI6Ii81NTY5NTg0NS8yOTYxMDQ2MjQtYzVmM2UxOTAtOWI1ZS00OTNkLThmNjgtMTgwYWM3MDhjZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEzMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMThjOGQyMWIzMzEzODQ0Yjc5MTg3N2YzMDgxMjdiOGY2MDllZDk2MjNhYWVmMTgzYjk5Nzk0MGI1NTNlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uX4qud1MGluIxnQXOZDIazdSh9-lClDMq7zzN_R6cmU)

Hello, I encountered an error when running at this point. 

My code is as follows:
(flow) sys-vis@sysvis-ThinkStation-P920:~/cotv/CoTV/evaluation$ python outputFilesProcessing.py
Traceback (most recent call last):
  File "outputFilesProcessing.py", line 180, in &lt;module&gt;
    main(sys.argv[1:])
  File "outputFilesProcessing.py", line 176, in main
    raise ValueError("Unable to find necessary options: --scen, and --horizon.")
ValueError: Unable to find necessary options: --scen, and --horizon.

 May I ask how you run this code? What are the inputs for 'scene' and 'horizon' respectively

**Comment by xulw8** [comment]
> Hello, your code really helps me understand the traffic light signal control. These days I try to run your codes in 1x1 grid and 1x6 grid with the CoTV and PressLight, but why are the metric "Fuel consumption(l/100km)" results in my training quite different with your results described in the paper? I haven't do any modification in the code. Looking forward to communicating with you. Thanks very much. ![2024-01-11 09-35-36 的屏幕截图](https://private-user-images.githubusercontent.com/55695845/296104624-c5f3e190-9b5e-493d-8f68-180ac708cde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODQ4MDcsIm5iZiI6MTczNTE4NDUwNywicGF0aCI6Ii81NTY5NTg0NS8yOTYxMDQ2MjQtYzVmM2UxOTAtOWI1ZS00OTNkLThmNjgtMTgwYWM3MDhjZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDAzNDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNDMzODc5YzgzOTRlNTM0NjA4OWQ4YjhiMmQ4ZmZlZGUxYWM0NTU5N2E1ZmYyMDU1NmUwZjgwMWVlNGNiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZGzvWP-1pygGx0tA8pa3EQxbt8husv-VLw8chOzD-fI)

你好，我看到您的屏幕截图是中文，因此用中文请教，请问怎么打开这个界面呢，我打开不了
